// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrbiyVen4FtBjQErgnffRG6f5TIbMcu9I',
    appId: '1:34831940096:web:a8330878996af2046676e5',
    messagingSenderId: '34831940096',
    projectId: 'book-ai-369bc',
    authDomain: 'book-ai-369bc.firebaseapp.com',
    storageBucket: 'book-ai-369bc.firebasestorage.app',
    measurementId: 'G-FYSTWYXHRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5GF1iC9j_RByg5PiPxTczPZu0yBQcjAo',
    appId: '1:34831940096:android:6e4b58cd715aba1c6676e5',
    messagingSenderId: '34831940096',
    projectId: 'book-ai-369bc',
    storageBucket: 'book-ai-369bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIZUKTP0-g_cr3ja27fJ7FhG9u63l4qA',
    appId: '1:34831940096:ios:6dc6543b6ace78776676e5',
    messagingSenderId: '34831940096',
    projectId: 'book-ai-369bc',
    storageBucket: 'book-ai-369bc.firebasestorage.app',
    iosBundleId: 'com.example.bookedAi',
  );
}
